### ISSUE TITLE
sdk更新沒有通知, 也沒有上tag標記release

### ISSUE THREAD

**Issue by Calvin-Huang** [allpay/PHP#3]
下載連結頁面內沒有標記版號 ![no-version](https://dl.dropboxusercontent.com/u/108987767/images/no-version.png)
在github上面也沒有release tag，這樣對直接使用sdk的來做商業行為開發者來說非常危險
很有可能一次hotfix沒follow到就造成莫大的損失

建議依照 [語意化版本](http://semver.org/lang/zh-TW/) 規範下去標記version

**Comment by AllennChang** [comment]
感謝你提供的建議，我們會在安排改進，謝謝
