### ISSUE TITLE
CheckOutString parameters mismatched

### ISSUE THREAD

**Issue by ethanliu** [allpay/PHP#5]
line: 514

`return` Send::CheckOutString($paymentButton,$target = "_self",$arParameters,$this->SendExtend,$this->ServiceURL,$this->HashKey,$this->HashIV);

Should be 

`return` Send::CheckOutString($paymentButton,$target = "_self",$arParameters,$this->SendExtend,$this->HashKey,$this->HashIV,$this->ServiceURL);

**Comment by AllennChang** [comment]
感謝你的通知 ,我會反應給我們的開發團隊
